name = "UniversalDecimalTime"
uuid = "d043980c-0306-46ab-b81e-01bd676f65fc"
authors = ["imohag9 <souidi.hamza90@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Dates = "1.11"
Printf = "1.11"
julia = "1.11"
